######################################################################
# Automatically generated by qmake (3.0) Sat Aug 8 17:53:19 2015
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
QT += core gui widgets
# Input
SOURCES += hello.cpp
